# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882f0a931f0e89c66ad2d79e32d3a194618183ad1cc03077484d35430ffd664f9bfccd694818ddc8ac517a741c1f0165f1e3ada08344a8ea7be0b3c512b5850e

test:
  secret_key_base: 58f837116fd8ddace5c9951bc95dd67d480e067e94a85e3a02f3574b9ec854bec3b47a5fd3afe4bfb904c6b4521b992b4e89d817dcf4cab5a2079c38281c6c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
